### ISSUE TITLE
[Android] Failed to load WebView provider: No WebView installed

### ISSUE THREAD

**Issue by marf** [react-native-cookies/cookies#112]
Hello,
for some users on Android we get this crash since they do not have any WebView installed:

```
Fatal Exception: android.util.AndroidRuntimeException: android.webkit.WebViewFactory$MissingWebViewPackageException: Failed to load WebView provider: No WebView installed
       at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:435)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
       at android.webkit.CookieManager.getInstance(CookieManager.java:47)
       at com.reactnativecommunity.cookies.CookieManagerModule.<init>(CookieManagerModule.java:52)
       at com.reactnativecommunity.cookies.CookieManagerPackage.createNativeModules(CookieManagerPackage.java:30)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1347)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1318)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1240)
       at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:131)
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1023)
       at java.lang.Thread.run(Thread.java:919)
```

Is it possible to release a version of the package where this crash is trapped so that it does not result in a crash.

**Comment by capezzbr** [comment]
Experiencing the same issue

**Comment by capezzbr** [comment]
Made a PR https://github.com/react-native-cookies/cookies/pull/119

**Comment by safaiyeh** [comment]
Closing as the PR was merged. Thanks again @capezzbr
