### ISSUE TITLE
RNCookieManagerAndroid.set got 4 arguments, expected 5

### ISSUE THREAD

**Issue by javierbustamante** [react-native-cookies/cookies#84]
Helo!!!

I've update the library to 5.0.1 (also cleaning projects, pod install, and everything) but always I get the same error (on iOS too).

RNCookieManagerAndroid.set got 4 arguments, expected 5

with the next trace:

```
com.facebook.react.bridge.NativeArgumentsParseException: RNCookieManagerAndroid.set got 4 arguments, expected 5
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:349)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
```

Help, please!!!

Thank you!!!

**Comment by javierbustamante** [comment]
I solved with the classic:
```
rm -rf node_modules/
rm -rf ios/Pods/
npm i
cd ios/ && pod install && cd ..
```

Thank you!!!
